#theme: dopetrope - By HTML5UP https://html5up.net/dopetrope
title: "Alex Ward"
name: "Alex Ward"
greeting: "Greeting"
tag-line: "Tag line"
permalink: pretty


collections:
  featured:
    output: true
